apiVersion: v2
name: rust-api
description: A Helm chart for deploying the Rust API service
type: application
version: 0.1.0              # chart version (independent of your app version)
appVersion: "1.0.0"         # optional — your Rust app version (e.g. cargo release)
maintainers:
  - name: Sanzor
    email: you@example.com
sources:
  - https://github.com/sanzor/rust-api
home: https://github.com/sanzor/rust-api
keywords:
  - rust
  - api
  - backend
annotations:
  category: backend
  argocd.argoproj.io/sync-wave: "1"

