[package]
name="player"
version = "0.1.0"
edition = "2021"

[dependencies]
dsp-domain={path="../dsp-domain"}
audiolib={path = "../audiolib"}
rstest="0.25"
cpal = "0.15"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"