[package]
name = "data-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
audiolib = { path = "../audiolib" }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }
async-trait = "0.1"
ulid = "1"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
