[package]
name="dsp-core"
version="0.1.0"
edition ="2021"

[dependencies]
audiolib={path="../audiolib"}
dsp-domain={path = "../dsp-domain"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rstest="0.25"