BEGIN;

DROP TABLE IF EXISTS graph_edges;
DROP TABLE IF EXISTS graph_nodes;
DROP TABLE IF EXISTS graphs;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS region_sets;
DROP TABLE IF EXISTS tracks;

COMMIT;

