[package]
name="data-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }
kameo="0.17.2"
domain={path = "../domain"}
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
ulid="1"
jsonwebtoken = "9"
chrono = "0.4"
hound="3.5.1"
audiolib={path = "../audiolib"}