[package]
name = "dsp-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
async-std = { version = "1", features = ["attributes"] }
actix-rt = "2"
actix="0.13"
actix-http="3"
actix-session = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rstest="0.25"
kameo="0.17.2"
actors={path = "../actors"}
domain={path="../domain"}
dsp-core={path="../dsp-core"}
ulid="1"
dotenv = "0.15"
reqwest = { version = "0.12.22", features = ["json"] }
jsonwebtoken = "9"
oauth2 = "5.0.0"
audiolib={path = "../audiolib"}