[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4"
actix-multipart="0.7.2"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
async-std = { version = "1", features = ["attributes"] }
actix-rt = "2"
actix="0.13"
actix-http="3"
actix-cors="0.7.1"
actix-ws="0.3.0"
actix-session = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rstest="0.26.1"
kameo="0.17.2"
actors={path = "../actors"}
domain={path="../domain"}
ulid="1"
dotenv = "0.15"
jsonwebtoken = "9"
audiolib={path = "../audiolib"}
player={path="../player"}
bytemuck="1.23.1"
tokio-tungstenite = "0.27"
url = "2"
futures-util = "0.3"
urlencoding = "2"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
httpmock = "0.7.0"
data-provider={path="../data-provider"}
mockall = "0.13.1"
chrono = "0.4"
rand = "0.9.2"
base64 = "0.22.1"
mime_guess = "2"